### PR TITLE
Patch to add days remaining until next billing cycle and percentage bandwidth used

### PR DESCRIPTION
**Pull request by deftdawg**

### CODE REVIEW

**Comment by Norien** [comment]
Just tested, my csv output is missing the total usage - ```684.11,24.61,,708.72,0,0,0```

how ever if If I run without param I get correct output
```
Downloaded: 684.11 GB
Uploaded: 24.61 GB
Total Usage: 708.72 GB
Usage Cap: Unlimited
Percentage Used: 0 %
Days Remaining: 0 days
```

**Comment by deftdawg** [comment]
@Norien  FYI, I realized later that the order cap and total in the csv switched... so you need to update your HA config like this:

```
  - platform: template
    sensors:
      usage_downloaded:
        friendly_name: "Rogers Usage: Downloaded"
        value_template: "{{states.sensor.usage.state.split(',')[0]}}"
        unit_of_measurement: "GB"
      usage_uploaded:
        friendly_name: "Rogers Usage: Uploaded"
        value_template: "{{states.sensor.usage.state.split(',')[1]}}"
        unit_of_measurement: "GB"
      usage_remaining_usage:
        friendly_name: "Rogers Usage: Remaining Bandwidth"
        value_template: "{{states.sensor.usage.state.split(',')[2]}}"
        unit_of_measurement: "GB"
      usage_total_usage:
        friendly_name: "Rogers Usage: Total Bandwidth"
        value_template: "{{states.sensor.usage.state.split(',')[3]}}"
        unit_of_measurement: "GB"
      usage_usage_cap:
        friendly_name: "Rogers Usage: Cap"
        value_template: "{{states.sensor.usage.state.split(',')[4]}}"
        unit_of_measurement: "GB"
      usage_percentage_used:
        friendly_name: "Rogers Usage: Percentage Used"
        value_template: "{{states.sensor.usage.state.split(',')[5]}}"
        unit_of_measurement: "%"
      usage_days_remaining:
        friendly_name: "Rogers Usage: Days Remaining"
        value_template: "{{states.sensor.usage.state.split(',')[6]}}"
        unit_of_measurement: "Days"
```

**Comment by Norien** [comment]
She is beautiful, thanks for the help!
capture
https://github.com/Norien/Home-Assistant-Config/blob/master/packages/network.yaml for config ( I used some icon templates to keep it a little cleaner )

**Comment by Norien** [comment]
jumpkick I saw an issue with the ```Days Remaining``` sensor at the end of my billing period went to -1 because the rogers page is always 1 day behind maybe?

**Comment by deftdawg** [comment]
@Norien Just added +1 to the days remaining, the easiest way to fix it, let me know if it looks good... my billing date isn't for another couple weeks.

**Pull request closed without merging**
